-   id: version-bump
    name: UV Workspace Version Bump
    entry: version-bump.py
    language: python
    description: >-
        Automatically bumps patch versions for changed packages in a UV workspace
        and the root project if any sub-packages are bumped. Uses tomlkit to preserve formatting.
    args: [] 
    additional_dependencies: ["tomlkit>=0.12.0,<1.0.0"]