repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a recent tag
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0 # Use a recent tag for ruff
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Add the local hook itself to ensure it runs on this repo.
  # This is more of a sanity check; its real test is in other repos.
  - repo: local
    hooks:
      - id: version-bump
        name: Local Version Bump (Self-Test)
        entry: version-bump.py
        language: python
        args:
          # For self-testing, we don't want to bump the root pyproject.toml (if it existed and were a package)
          # This repo doesn't have a conventional package structure for the hook to act upon,
          # so the main goal is to ensure the script runs without errors.
          - "--dont-bump-root"
          # Example of using --ignore-dirs if we had specific test utility dirs with pyproject.toml:
          # - "--ignore-dirs"
          # - "^test_utils/.*" # Ignore a potential test_utils directory
          # No specific --ignore-package-dirs needed here, as the hook should correctly
          # identify no sub-packages to bump after excluding the root project itself.
          # If we had a dummy pyproject.toml for testing in e.g. `test_pkg/pyproject.toml`,
          # we might add `--ignore-package-dirs` for other test utility folders. 