[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
    name = "workspace-version-bump-hook"
    version = "0.1.0"
    description = "A pre-commit hook for bumping versions in a workspace."
    dependencies = [
        "tomlkit>=0.12.0,<1.0.0",
    ]